// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUOdVPijjZEcJ82_vFCjV3DRSlMA-THes',
    appId: '1:620945493886:web:27f076092e96f7e322ed2f',
    messagingSenderId: '620945493886',
    projectId: 'fitnesx-fe30d',
    authDomain: 'fitnesx-fe30d.firebaseapp.com',
    storageBucket: 'fitnesx-fe30d.firebasestorage.app',
    measurementId: 'G-5MTB6ZQP40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxmhzZD90KRndKHblX16qxuM_E5Kb05AI',
    appId: '1:620945493886:android:26abda42c00d3d4d22ed2f',
    messagingSenderId: '620945493886',
    projectId: 'fitnesx-fe30d',
    storageBucket: 'fitnesx-fe30d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJWaOEqyoFote5b1a_A-EV6B5nAkSkPXQ',
    appId: '1:620945493886:ios:e6e10427ba94926322ed2f',
    messagingSenderId: '620945493886',
    projectId: 'fitnesx-fe30d',
    storageBucket: 'fitnesx-fe30d.firebasestorage.app',
    iosClientId: '620945493886-v58l3efre3ots49ke25i2fkesuraobqn.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUOdVPijjZEcJ82_vFCjV3DRSlMA-THes',
    appId: '1:620945493886:web:d8cc82ca5025d77022ed2f',
    messagingSenderId: '620945493886',
    projectId: 'fitnesx-fe30d',
    authDomain: 'fitnesx-fe30d.firebaseapp.com',
    storageBucket: 'fitnesx-fe30d.firebasestorage.app',
    measurementId: 'G-PMD1STVNTK',
  );
}
