name: calendar_agenda
description: Calendar agenda widget with a lot of customizable styles, also can be put as appbar widget.
version: 0.0.3
homepage: https://github.com/sud0su/calendar_agenda
repository: https://github.com/sud0su/calendar_agenda
issue_tracker: https://github.com/sud0su/calendar_agenda/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

# Tambahkan informasi tambahan untuk pub.dev
topics:
  - calendar
  - agenda
  - widget
  - ui
  - date-picker

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux: